### ISSUE TITLE
Adapt code to CCT stripe that does not allow both cw and ww to be 100% (due to temperature overload)

### ISSUE THREAD

**Issue by mngsps** [gfrancesco/cwww-template-light-ha#3]
Hi @gfrancesco,

thank you a lot for this great code and for sharing!
In my case, manufacturer of the CCT stripe sais, one should not use it wit both cw and ww set to 100% due to temperature overload.
So the LED controller I'm actually using sets cw and ww to both 50% in case of averaged temperature value and full brightness.
If I got you right, this is one part you DID NOT want to happen. In my case, I would like this to happen (100% cct brightness should be the sum of both cw and ww brightness).
Could you help me adopting the code for this purpose?
When using your code, the brightness automatically changes to 50% when changing temperature to 2700 or 6500K, and I guess this is what you wanted to happen. But as I mentioned, this doesn't favor my stripes.

Would be great to have your help.

Thank you a lot and all the best
Benedikt

**Comment by gfrancesco** [comment]
This template was created exactly to avoid that kind of power limitation. Maybe you can try to use this other template, it should work as you need: https://community.home-assistant.io/t/create-a-temperature-changing-light-from-2-lights-and-shelly-rgbw2-solved

The other option would be to never go over 50% of brightness, see the blog post to understand how brightness is calculated.
